// pages/TermsOfUse.jsx
// Premium Terms of Service page

import { motion } from "framer-motion";
import { DocumentTextIcon } from "@heroicons/react/24/outline";
import SEO from "../components/SEO";

export default function TermsOfUse() {
    const fadeInUp = {
        hidden: { opacity: 0, y: 30 },
        visible: { opacity: 1, y: 0 },
    };

    const sections = [
        {
            title: "1. Acceptance of Terms",
            content: `Kantevo connects college/school students with registered canteens to browse menus, place advance orders, and pay digitally. Kantevo is a technology facilitator and not a food manufacturer, seller, or delivery provider. By using the Platform, you enter a legally binding agreement with Kantevo and accept all policies linked on the Platform.`,
        },
        {
            title: "2. Definitions",
            content: null,
            list: [
                { term: '"User" / "You"', def: "Anyone using the Platform (students, canteen owners, or visitors)." },
                { term: '"Canteen Partner"', def: "A verified college/school canteen registered on Kantevo." },
                { term: '"Order"', def: "A confirmed request by a student to a Canteen Partner through the Platform." },
                { term: '"Platform"', def: "Kantevo's website, mobile applications, and APIs." },
                { term: '"Content"', def: "Menus, images, reviews, data, messages, and media uploaded by Users or Canteen Partners." },
            ],
        },
        {
            title: "3. Eligibility",
            content: `Students must be at least 16 years old and belong to a participating institution. Canteen Partners must be institution-authorized and verified by Kantevo. All Users must comply with Indian laws, including the Information Technology Act, 2000 and the Consumer Protection Act, 2019.`,
        },
        {
            title: "4. Changes to the Terms",
            content: `We may update these Terms as our services evolve. Continued use of the Platform after updates means you accept the revised Terms. Please review this page periodically.`,
        },
        {
            title: "5. Provision of Services",
            content: `Kantevo enables discovery of campus canteens, digital menu browsing, advance ordering, and payment. Kantevo does not cook, pack, or deliver food; these are handled by Canteen Partners. Services may be modified, paused, or removed at any time to improve the experience or for operational reasons.`,
            note: "Disclaimer: Kantevo is a technology platform. Food preparation, pricing, availability, and quality remain solely the responsibility of the respective Canteen Partner.",
        },
        {
            title: "6. User Accounts",
            content: null,
            bullets: [
                "Account creation requires valid details and verification (students via institutional identity; canteens via authorization).",
                "You are responsible for safeguarding passwords and for all activity under your account.",
                "Impersonation, fake registrations, or misuse of tokens/payments may result in immediate suspension.",
                "We may send you essential communications (order status, service messages, security alerts).",
                "Kantevo may deactivate accounts for policy violations, fraud, or risk to the Platform or users.",
            ],
        },
        {
            title: "7. Content Ownership and Licensing",
            content: `You own the content you upload (e.g., reviews, menu photos, descriptions). By uploading, you grant Kantevo a non-exclusive, worldwide, royalty-free license to host, display, adapt, and promote such content for Platform functionality and communication. Kantevo owns all rights in its name, logos, interface, software, and databases. Unauthorized use, scraping, framing, or reproduction of Kantevo Content is prohibited.`,
        },
        {
            title: "8. Prohibited Activities",
            content: null,
            bullets: [
                "Posting offensive, misleading, infringing, or unlawful content.",
                "Impersonation, fake accounts, or misrepresentation of identity/affiliation.",
                "Circumventing payments or order tokens; chargebacks without basis.",
                "Using bots, scrapers, or automated scripts to access the Platform.",
                "Spamming, unsolicited promotions, or chain messages.",
                "Interfering with security features, APIs, or normal operation of the Platform.",
                "Any misuse that harms students, canteens, institutions, or Kantevo.",
            ],
        },
        {
            title: "9. Orders and Payments",
            content: `Orders placed via Kantevo are processed by the respective Canteen Partner. A collection token or QR generated by the Platform represents a confirmed order. Payments are facilitated through integrated third-party gateways; Kantevo does not handle cash or prepare food. Canteen Partners are solely responsible for fulfillment. Once an order is confirmed, cancellation and refunds (if any) are governed by our Refund & Cancellation Policy and the Canteen Partner's operational status.`,
        },
        {
            title: "10. Pricing, Cancellation, and Refund",
            content: null,
            bullets: [
                "Menu prices are listed by Canteen Partners; occasional discrepancies may occur at source.",
                "Confirmed orders cannot be modified except with Canteen Partner approval.",
                "No refunds for change of mind. Refunds may apply for non-fulfillment, item unavailability, or duplicate payment.",
                "Refund timelines depend on payment processors; Kantevo isn't liable for processor delays.",
            ],
        },
        {
            title: "11. Advertising and Promotions",
            content: `The Platform may display sponsored placements, coupons, or canteen highlights. Such content will be clearly identified where feasible. Your dealings with third-party advertisers are solely between you and them; Kantevo isn't responsible for external offers or charitable campaigns run outside the Platform.`,
        },
        {
            title: "12. Warranties and Liability",
            content: `The Platform is provided "as is" and "as available." We do not guarantee uninterrupted, timely, or error-free access. Food quality, taste, hygiene, and safety are the responsibility of Canteen Partners. To the maximum extent permitted by law, Kantevo is not liable for indirect, incidental, special, or consequential damages. You are responsible for your device, data, and internet charges.`,
        },
        {
            title: "13. Indemnification",
            content: `You agree to indemnify and hold harmless Kantevo, its team, and affiliates from any claims, losses, or liabilities arising from your misuse of the Platform, breach of these Terms, or violation of third-party rights. Kantevo may assume exclusive defense and control of matters subject to indemnification.`,
        },
        {
            title: "14. Account Termination",
            content: `You can delete your account at any time via in-app settings or by contacting support. Kantevo may suspend or terminate access for violations, fraud, or inactivity. Order and payment records may be retained as required by law and for legitimate business purposes.`,
        },
        {
            title: "15. General Terms",
            content: null,
            bullets: [
                "These Terms, along with our Privacy Policy and Refund & Cancellation Policy, form the entire agreement.",
                "If any provision is unenforceable, the remainder remains in effect.",
                "No partnership, employment, or agency relationship is created by these Terms.",
                "Governing Law: India; exclusive jurisdiction of the courts in India.",
                "Any claim must be initiated within one (1) year from when it arose.",
            ],
        },
        {
            title: "16. Copyright & IP Infringement",
            content: null,
            customContent: (
                <p className="text-text-secondary">
                    Kantevo respects intellectual property rights. If you believe your copyrighted work is used on the Platform without authorization, please email a detailed notice to{" "}
                    <a href="mailto:legal@kantevo.com" className="text-primary hover:underline">
                        legal@kantevo.com
                    </a>{" "}
                    including description of the work, proof of ownership, URL/screenshot, your contact details, and a statement made under good faith.
                </p>
            ),
        },
        {
            title: "17. Feedback and Suggestions",
            content: `We welcome product ideas and feedback. By submitting suggestions, you agree they are non-confidential and may be used by Kantevo without obligation to compensate or credit you. Please avoid sending unsolicited marketing proposals.`,
        },
        {
            title: "18. Contact & Grievance",
            content: null,
            customContent: (
                <div className="text-text-secondary space-y-2">
                    <p>Kantevo (Udyam Registered MSME)</p>
                    <p>
                        Email:{" "}
                        <a href="mailto:support@kantevo.com" className="text-primary hover:underline">
                            support@kantevo.com
                        </a>
                    </p>
                    <p>Response Time: within 48 business hours</p>
                    <p>Operating Hours: Mon–Fri, 10:00 AM–6:00 PM (IST)</p>
                    <p className="pt-2">
                        For legal notices:{" "}
                        <a href="mailto:legal@kantevo.com" className="text-primary hover:underline">
                            legal@kantevo.com
                        </a>
                    </p>
                </div>
            ),
        },
        {
            title: "19. Anti-Fraud & Safety Notice",
            content: null,
            customContent: (
                <p className="text-text-secondary">
                    Kantevo representatives will never ask for your OTP, card PIN, full card number, or passwords. If you receive such a request, do not share any information and report it immediately to{" "}
                    <a href="mailto:security@kantevo.com" className="text-primary hover:underline">
                        security@kantevo.com
                    </a>.
                </p>
            ),
        },
    ];

    return (
        <div className="min-h-screen bg-background text-text">
            <SEO
                title="Terms of Service — Kantevo"
                description="Kantevo Terms of Service: user rights, responsibilities, and platform policies for our campus canteen ordering experience."
                canonicalPath="/terms-of-service"
            />

            {/* Hero Section */}
            <section className="relative overflow-hidden hero-pattern">
                <div className="absolute top-20 right-10 w-72 h-72 bg-primary/10 rounded-full blur-3xl" />

                <div className="container-app relative">
                    <div className="py-12 md:py-16 lg:py-20">
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ duration: 0.5 }}
                            className="max-w-3xl mx-auto text-center"
                        >
                            <div className="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-6">
                                <DocumentTextIcon className="w-8 h-8 text-primary" />
                            </div>
                            <h1 className="heading-xl mb-6">
                                Terms of <span className="text-gradient">Service</span>
                            </h1>
                            <p className="text-sm text-text-muted mb-2">
                                Operated by: <strong className="text-text">Kantevo</strong> (Registered under Udyam MSME Scheme, India)
                            </p>
                            <p className="text-sm text-text-muted mb-4">Last updated: November 2025</p>
                            <p className="text-text-secondary">
                                Welcome to Kantevo — a digital platform that helps students pre-order
                                from verified campus canteens. By accessing or using Kantevo's website,
                                mobile app, or related APIs, you agree to these Terms of Service.
                            </p>
                        </motion.div>
                    </div>
                </div>
            </section>

            {/* Content */}
            <section className="py-12 md:py-16">
                <div className="container-app">
                    <div className="max-w-3xl mx-auto space-y-8">
                        {sections.map((section, i) => (
                            <motion.div
                                key={i}
                                initial="hidden"
                                whileInView="visible"
                                viewport={{ once: true, margin: "-50px" }}
                                variants={fadeInUp}
                                className="card p-6 md:p-8"
                            >
                                <h2 className="font-bold text-xl mb-4">{section.title}</h2>

                                {section.content && (
                                    <p className="text-text-secondary whitespace-pre-line">{section.content}</p>
                                )}

                                {section.customContent && section.customContent}

                                {section.note && (
                                    <p className="mt-4 p-4 rounded-xl bg-warning/10 text-warning text-sm">
                                        <strong>Disclaimer:</strong> {section.note.replace("Disclaimer: ", "")}
                                    </p>
                                )}

                                {section.list && (
                                    <div className="space-y-2">
                                        {section.list.map((item, j) => (
                                            <p key={j} className="text-text-secondary">
                                                <strong className="text-text">{item.term}:</strong> {item.def}
                                            </p>
                                        ))}
                                    </div>
                                )}

                                {section.bullets && (
                                    <ul className="space-y-2">
                                        {section.bullets.map((bullet, j) => (
                                            <li key={j} className="flex items-start gap-2 text-text-secondary">
                                                <span className="text-primary mt-1">•</span>
                                                {bullet}
                                            </li>
                                        ))}
                                    </ul>
                                )}
                            </motion.div>
                        ))}
                    </div>
                </div>
            </section>
        </div>
    );
}
